version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - desafio-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - desafio-network
    depends_on:
      - app

  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d # na primeira execução, o volume 'mysql' tem que estar vazio
                                             #  conforme descrito em https://stackoverflow.com/a/39765233/9205969
    environment: 
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio-network

networks: 
  desafio-network:
    driver: bridge

